In [1]:
import kagglehub
from kagglehub import KaggleDatasetAdapter

file_path = "Housing.csv"


df = kagglehub.load_dataset(
  KaggleDatasetAdapter.PANDAS,
  "yasserh/housing-prices-dataset",
  file_path,
)

print("First 5 records:", df.head())

/tmp/ipython-input-1-2252120355.py:7: DeprecationWarning: load_dataset is deprecated and will be removed in a future version.
  df = kagglehub.load_dataset(

First 5 records:       price  area  bedrooms  bathrooms  stories mainroad guestroom basement  \
0  13300000  7420         4          2        3      yes        no       no
1  12250000  8960         4          4        4      yes        no       no
2  12250000  9960         3          2        2      yes        no      yes
3  12215000  7500         4          2        2      yes        no      yes
4  11410000  7420         4          1        2      yes       yes      yes

  hotwaterheating airconditioning  parking prefarea furnishingstatus
0              no             yes        2      yes        furnished
1              no             yes        3       no        furnished
2              no              no        2      yes   semi-furnished
3              no             yes        3      yes        furnished
4              no             yes        2       no        furnished

In [2]:
display(df.head())
display(df.isnull().sum())
display(df.describe())

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished

price               0
area                0
bedrooms            0
bathrooms           0
stories             0
mainroad            0
guestroom           0
basement            0
hotwaterheating     0
airconditioning     0
parking             0
prefarea            0
furnishingstatus    0
dtype: int64

,price,area,bedrooms,bathrooms,stories,parking
count,5.450000e+02,545.000000,545.000000,545.000000,545.000000,545.000000
mean,4.766729e+06,5150.541284,2.965138,1.286239,1.805505,0.693578
std,1.870440e+06,2170.141023,0.738064,0.502470,0.867492,0.861586
min,1.750000e+06,1650.000000,1.000000,1.000000,1.000000,0.000000
25%,3.430000e+06,3600.000000,2.000000,1.000000,1.000000,0.000000
50%,4.340000e+06,4600.000000,3.000000,1.000000,2.000000,0.000000
75%,5.740000e+06,6360.000000,3.000000,2.000000,2.000000,1.000000
max,1.330000e+07,16200.000000,6.000000,4.000000,4.000000,3.000000

In [3]:
import pandas as pd
categorical_cols = df.select_dtypes(include='object').columns
df = pd.get_dummies(df, columns=categorical_cols, drop_first=True)
display(df.head())

,price,area,bedrooms,bathrooms,stories,parking,mainroad_yes,guestroom_yes,basement_yes,hotwaterheating_yes,airconditioning_yes,prefarea_yes,furnishingstatus_semi-furnished,furnishingstatus_unfurnished
0,13300000,7420,4,2,3,2,True,False,False,False,True,True,False,False
1,12250000,8960,4,4,4,3,True,False,False,False,True,False,False,False
2,12250000,9960,3,2,2,2,True,False,True,False,False,True,True,False
3,12215000,7500,4,2,2,3,True,False,True,False,True,True,False,False
4,11410000,7420,4,1,2,2,True,True,True,False,True,False,False,False

In [22]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

X = df.drop('price', axis=1)
y = df['price']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=50)

model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

**Reasoning**:
Access the coefficients and feature names, then print them to interpret their impact on house price.

In [5]:
coefficients = model.coef_
features = X_train.columns

for feature, coef in zip(features, coefficients):
    print(f"{feature}: {coef}")

area: 235.9688045413957
bedrooms: 76778.7016343784
bathrooms: 1094444.7861005957
stories: 407476.59498491115
parking: 224841.91327662673
mainroad_yes: 367919.9476795722
guestroom_yes: 231610.0371756495
basement_yes: 390251.17618109327
hotwaterheating_yes: 684649.8853387912
airconditioning_yes: 791426.7358431868
prefarea_yes: 629890.5653133605
furnishingstatus_semi-furnished: -126881.81758510851
furnishingstatus_unfurnished: -413645.062228222

In [6]:
import pandas as pd

coef_df = pd.DataFrame({'Feature': features, 'Coefficient': coefficients})
coef_df['Absolute_Coefficient'] = abs(coef_df['Coefficient'])
coef_df = coef_df.sort_values(by='Absolute_Coefficient', ascending=False)

print("Model Coefficients and Interpretation:")
print(coef_df[['Feature', 'Coefficient']])
print("\nInterpretation:")
print("- A positive coefficient indicates that as the feature increases, the house price tends to increase, holding other features constant.")
print("- A negative coefficient indicates that as the feature increases, the house price tends to decrease, holding other features constant.")

print("\nKey Findings:")
print("- The features with the largest absolute coefficients have the most significant impact on the predicted house price.")
print(f"- Based on the absolute values, the features with the most significant positive impact are: {coef_df.iloc[0]['Feature']}, {coef_df.iloc[1]['Feature']}, and {coef_df.iloc[2]['Feature']}")
print(f"- The features with the most significant negative impact are: {coef_df.iloc[-1]['Feature']} and {coef_df.iloc[-2]['Feature']}")

Model Coefficients and Interpretation:
                            Feature   Coefficient
2                         bathrooms  1.094445e+06
9               airconditioning_yes  7.914267e+05
8               hotwaterheating_yes  6.846499e+05
10                     prefarea_yes  6.298906e+05
12     furnishingstatus_unfurnished -4.136451e+05
3                           stories  4.074766e+05
7                      basement_yes  3.902512e+05
5                      mainroad_yes  3.679199e+05
6                     guestroom_yes  2.316100e+05
4                           parking  2.248419e+05
11  furnishingstatus_semi-furnished -1.268818e+05
1                          bedrooms  7.677870e+04
0                              area  2.359688e+02

Interpretation:
- A positive coefficient indicates that as the feature increases, the house price tends to increase, holding other features constant.
- A negative coefficient indicates that as the feature increases, the house price tends to decrease, holding other features constant.

Key Findings:
- The features with the largest absolute coefficients have the most significant impact on the predicted house price.
- Based on the absolute values, the features with the most significant positive impact are: bathrooms, airconditioning_yes, and hotwaterheating_yes
- The features with the most significant negative impact are: area and bedrooms

In [21]:
from sklearn.metrics import mean_squared_error, r2_score

y_pred = model.predict(X_test)

mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print("Mean Squared Error:", mse)
print("R-squared:", r2)

Mean Squared Error: 976484771024.6128
R-squared: 0.6611214250980098

In [8]:
coefficients = model.coef_
features = X.columns

for feature, coef in zip(features, coefficients):
    print(f"{feature}: {coef}")

area: 235.9688045413957
bedrooms: 76778.7016343784
bathrooms: 1094444.7861005957
stories: 407476.59498491115
parking: 224841.91327662673
mainroad_yes: 367919.9476795722
guestroom_yes: 231610.0371756495
basement_yes: 390251.17618109327
hotwaterheating_yes: 684649.8853387912
airconditioning_yes: 791426.7358431868
prefarea_yes: 629890.5653133605
furnishingstatus_semi-furnished: -126881.81758510851
furnishingstatus_unfurnished: -413645.062228222

In [9]:
import pandas as pd

coef_df = pd.DataFrame({'Feature': features, 'Coefficient': coefficients})
coef_df['Absolute_Coefficient'] = abs(coef_df['Coefficient'])
coef_df = coef_df.sort_values(by='Absolute_Coefficient', ascending=False)

print("Model Coefficients and Interpretation:")
print(coef_df[['Feature', 'Coefficient']])
print("\nInterpretation:")
print("- A positive coefficient indicates that as the feature increases, the house price tends to increase, holding other features constant.")
print("- A negative coefficient indicates that as the feature increases, the house price tends to decrease, holding other features constant.")

print("\nKey Findings:")
print("- The features with the largest absolute coefficients have the most significant impact on the predicted house price.")
print(f"- Based on the absolute values, the features with the most significant positive impact are: {coef_df.iloc[0]['Feature']}, {coef_df.iloc[1]['Feature']}, and {coef_df.iloc[2]['Feature']}")
print(f"- The features with the most significant negative impact are: {coef_df.iloc[-1]['Feature']} and {coef_df.iloc[-2]['Feature']}")

Model Coefficients and Interpretation:
                            Feature   Coefficient
2                         bathrooms  1.094445e+06
9               airconditioning_yes  7.914267e+05
8               hotwaterheating_yes  6.846499e+05
10                     prefarea_yes  6.298906e+05
12     furnishingstatus_unfurnished -4.136451e+05
3                           stories  4.074766e+05
7                      basement_yes  3.902512e+05
5                      mainroad_yes  3.679199e+05
6                     guestroom_yes  2.316100e+05
4                           parking  2.248419e+05
11  furnishingstatus_semi-furnished -1.268818e+05
1                          bedrooms  7.677870e+04
0                              area  2.359688e+02

Interpretation:
- A positive coefficient indicates that as the feature increases, the house price tends to increase, holding other features constant.
- A negative coefficient indicates that as the feature increases, the house price tends to decrease, holding other features constant.

Key Findings:
- The features with the largest absolute coefficients have the most significant impact on the predicted house price.
- Based on the absolute values, the features with the most significant positive impact are: bathrooms, airconditioning_yes, and hotwaterheating_yes
- The features with the most significant negative impact are: area and bedrooms

In [11]:
import joblib

# Save the trained model to a file
filename = 'linear_regression_model.pkl'
joblib.dump(model, filename)

print(f"Model saved to {filename}")

Model saved to linear_regression_model.pkl

In [ ]:
!pip install fastapi nest-asyncio pyngrok uvicorn

In [ ]:
import joblib
import pandas as pd
from fastapi import FastAPI
from pydantic import BaseModel
import nest_asyncio
from pyngrok import ngrok
import uvicorn
from fastapi.middleware.cors import CORSMiddleware

# Load model
model = joblib.load('linear_regression_model.pkl')

# Create FastAPI app
app = FastAPI()

# CORS configuration - Add this BEFORE any routes
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],  # In production, specify exact origins
    allow_credentials=True,
    allow_methods=["GET", "POST", "PUT", "DELETE", "OPTIONS"],
    allow_headers=["*"],
)

class HousingFeatures(BaseModel):
    area: float
    bedrooms: int
    bathrooms: int
    stories: int
    mainroad: str
    guestroom: str
    basement: str
    hotwaterheating: str
    airconditioning: str
    parking: int
    prefarea: str
    furnishingstatus: str

# Add a root endpoint for testing
@app.get("/")
def read_root():
    return {"message": "Housing Price Prediction API is running"}

# Add OPTIONS handler for preflight requests
@app.options("/predict/")
def options_predict():
    return {"message": "OK"}

@app.post("/predict/")
def predict_price(features: HousingFeatures):
    try:
        # Convert features to the format expected by your model
        feature_data = {
            'area': features.area,
            'bedrooms': features.bedrooms,
            'bathrooms': features.bathrooms,
            'stories': features.stories,
            'parking': features.parking,
            'mainroad_yes': 1 if features.mainroad.lower() == 'yes' else 0,
            'guestroom_yes': 1 if features.guestroom.lower() == 'yes' else 0,
            'basement_yes': 1 if features.basement.lower() == 'yes' else 0,
            'hotwaterheating_yes': 1 if features.hotwaterheating.lower() == 'yes' else 0,
            'airconditioning_yes': 1 if features.airconditioning.lower() == 'yes' else 0,
            'prefarea_yes': 1 if features.prefarea.lower() == 'yes' else 0,
            'furnishingstatus_semi-furnished': 1 if features.furnishingstatus.lower() == 'semi-furnished' else 0,
            'furnishingstatus_unfurnished': 1 if features.furnishingstatus.lower() == 'unfurnished' else 0,
        }

        # Create DataFrame and make prediction
        input_df = pd.DataFrame([feature_data])
        prediction = model.predict(input_df)[0]

        return {"predicted_price": float(prediction)}

    except Exception as e:
        return {"error": str(e)}

if __name__ == "__main__":
    # Apply nest_asyncio for Jupyter/Colab environments
    nest_asyncio.apply()

    # Set up ngrok tunnel
    # ngrok.set_auth_token("your_auth_token_here")  # Uncomment and add your token
    ngrok_tunnel = ngrok.connect(8000)
    print(f'Public URL: {ngrok_tunnel.public_url}')

    # Run the server
    uvicorn.run(app, host="0.0.0.0", port=8000)

Public URL: https://475e6770b4e4.ngrok-free.app

INFO:     Started server process [590]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)

INFO:     103.120.162.35:0 - "OPTIONS /predict HTTP/1.1" 200 OK
INFO:     103.120.162.35:0 - "POST /predict HTTP/1.1" 307 Temporary Redirect
INFO:     103.120.162.35:0 - "OPTIONS /predict/ HTTP/1.1" 200 OK
INFO:     103.120.162.35:0 - "POST /predict/ HTTP/1.1" 200 OK